#let abbreviations = (
  /* (abbr: $A$, description: "符号描述"), */
  /* (abbr: $A$, description: [符号描述]), */
  (abbr: $frac(partial, partial x, style: "horizontal")$, description: "偏导数"),
  (abbr: $P (A|B)$, description: "在事件 B 发生的条件下事件 A 发生的概率"),
  (abbr: $theta$, description: "模型参数（如权重、偏置）"),
  (abbr: $gradient$, description: "梯度算子"),
  (abbr: $lambda$, description: "正则化系数（L1/L2 正则化）"),
  (abbr: $mu$, description: "均值"),
  (abbr: $sigma$, description: "标准差；激活函数（如 Sigmoid）"),
  (abbr: $eta$, description: "学习率（Learning Rate）"),
  (abbr: $infinity$, description: "无穷大"),
  (abbr: $sum$, description: "求和符号"),
  (abbr: $product$, description: "连乘符号"),
  (abbr: $epsilon$, description: "介电常数"),
  (abbr: $psi$, description: "波函数（量子力学）"),
  (abbr: $gradient times$, description: "旋度（向量场分析）"),
  (abbr: "ML", description: "机器学习（Machine Learning）"),
  (abbr: "DL", description: "深度学习（Deep Learning）"),
  (abbr: "AI", description: "人工智能（Artificial Intelligence）"),
  (abbr: "SGD", description: "随机梯度下降（Stochastic Gradient Descent）"),
  (abbr: "MLE", description: "最大似然估计（Maximum Likelihood Estimation）"),
  (abbr: "KL", description: "KL散度（Kullback-Leibler Divergence）"),
  (abbr: "MSE", description: "均方误差（Mean Squared Error）"),
  (abbr: "ROC", description: "受试者工作特征曲线（Receiver Operating Characteristic）"),
  (abbr: "AUC", description: "ROC曲线下面积（Area Under the ROC Curve）"),
  (abbr: "NN", description: "神经网络（Neural Network）"),
  (abbr: "CNN", description: "卷积神经网络（Convolutional Neural Network）"),
  (abbr: "RNN", description: "循环神经网络（Recurrent Neural Network）"),
  (abbr: "LSTM", description: "长短期记忆网络（Long Short-Term Memory）"),
  (abbr: "GRU", description: "门控循环单元（Gated Recurrent Unit）"),
  (abbr: "ReLU", description: "激活函数（Rectified Linear Unit）"),
  (abbr: "GAN", description: "生成对抗网络（Generative Adversarial Network）"),
  (abbr: "Dropout", description: "随机丢弃神经元"),
  (abbr: "LLM", description: "大语言模型（Large Language Model）"),
  (abbr: "BERT", description: "双向Transformer编码器（Bidirectional Encoder Representations from Transformers）"),
  (abbr: "GPT", description: "生成式预训练Transformer（Generative Pre-trained Transformer）"),
  (abbr: "ViT", description: "视觉Transformer（Vision Transformer）"),
  (abbr: "LoRA", description: "低秩适配（Low-Rank Adaptation）"),
  (abbr: "MoE", description: "专家混合（Mixture of Experts）"),
  (abbr: "FlashAttention", description: "高效注意力计算算法"),
  (abbr: "GPU", description: "图形处理器（Graphics Processing Unit）"),
  (abbr: "TPU", description: "张量处理器（Tensor Processing Unit）"),
  (abbr: "PyTorch", description: "深度学习框架"),
  (abbr: "JAX", description: "支持自动微分和GPU加速的数学库"),
)
